<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: sans-serif; color: #333; font-size: 12px; }
        .header { text-align: center; border-bottom: 2px solid #eee; padding-bottom: 20px; }
        .summary { margin: 20px 0; background: #f9f9f9; padding: 15px; border-radius: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #f4f4f4; text-align: left; padding: 10px; text-transform: uppercase; font-size: 10px; }
        td { padding: 10px; border-bottom: 1px solid #eee; }
        .text-right { text-align: right; }
        .footer { margin-top: 50px; text-align: center; font-size: 10px; color: #aaa; }
    </style>
</head>
<body>
    <div class="header">
        <h1>STYLEKART GLOBAL AUDIT</h1>
        <p>{{ $stats['type_label'] }} | {{ $stats['date_string'] }}</p>
    </div>
    <div class="summary">
        <p><strong>Platform Status:</strong> Operational</p>
        <p><strong>Total Records:</strong> {{ $stats['total_count'] }}</p>
        @if($type != 'vendors')
            <p><strong>Total Value:</strong> RS {{ number_format($stats['total_value'], 2) }}</p>
        @endif
    </div>
    <table>
        <thead>
            <tr>
                @if($type == 'wallets') <th>User</th><th>Balance</th> @else <th>Date</th><th>Vendor</th><th>Details</th><th class="text-right">Value</th> @endif
            </tr>
        </thead>
        <tbody>
            @foreach($results as $item)
            <tr>
                @if($type == 'wallets')
                    <td>{{ $item->user->name }}</td><td class="text-right">{{ number_format($item->balance, 2) }}</td>
                @else
                    <td>{{ $item->created_at->format('d/m/y') }}</td>
                    <td>{{ $item->vendor->name ?? 'N/A' }}</td>
                    <td>{{ $type == 'vendors' ? 'Vendor Account' : '#'.$item->order->order_number }}</td>
                    <td class="text-right">{{ number_format($type == 'vendors' ? $item->total_sales_count : ($item->price * $item->quantity), 2) }}</td>
                @endif
            </tr>
            @endforeach
        </tbody>
    </table>
    <div class="footer">Generated by Admin on {{ now()->format('d M Y H:i') }}</div>
</body>
</html>
